### ISSUE TITLE
More documentation on deploy keys please

### ISSUE THREAD

**Issue by woodie** [hatchboxio/github-hatchbox-deploy-action#2]
When we select `Custom` from repository details, there is a note about adding the cluster's SSH deploy key. With 4 parts to this (ssh-rsa, a-big-hash, [HatchBox], cluster-name), there should be some documentation about how exactly to set this up and test it... [this video](https://www.youtube.com/watch?v=qx1dHVtpCC0) does a good job explaining.

This action seems perfect for deploying to a cluster only when tests pass, but it's unclear how it should works otherwise (not using the action). Deployment should always be contingent on tests passing, right?

**Comment by excid3** [comment]
It's not an SSH, but the token in the URL on the app's Deploy tab in Hatchbox:

For example, it would show:
```
https://www.hatchbox.io/webhooks/github/push/XYZ
```

And you'd set `HATCHBOX_DEPLOY_KEY` to `XYZ` in your GitHub Secrets.

**Comment by excid3** [comment]
Added this to the README to clarify that. 👍
